### ISSUE TITLE
Hot reload for Frontend

### ISSUE THREAD

**Issue by brendancol** [makepath/makestack#12]
Is there currently a built in way within makestack for hotreload of the react app while doing development?

If not, lets add it!

**Comment by brendancol** [comment]
We may just need instructions for the user on how to approach frontend development using makestack

**Comment by jam-lock** [comment]
This feature is so useful that since version 4.x of create-react-app all react applications have by default hot reload implemented. And it's also implemented out-of-the-box for React Native.

[Here](https://github.com/makepath/makestack/blob/master/makestack/data/react/base/README.md) we have some basic information on how to run the frontend application.
I will also add some comments on how the frontend project is structured and some guides on creating basic map interactions
 with redux. But for any more specific use of maplibre-gl we should point out to their docs.
